import Head from 'next/head';
import { signOut } from 'next-auth/react';
import Header from '../components/Header';


export default function Home() {
  return (
    <div className='bg-gray-900'>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div>
        <Header />
      </div>

    
    </div>
  )
}
